import { Poppins } from "next/font/google";
import "./globals.css";
import { HeaderLanding } from "@/components/layout/HeaderLanding";
import { Footer } from "@/components/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "PadelPoint",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <HeaderLanding/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
